# Generated by Django 2.2 on 2020-10-21 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(verbose_name='Repository link')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Added')),
            ],
        ),
    ]
