# Generated by Django 2.2 on 2020-10-22 17:09

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('history_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitsHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit_id', models.CharField(max_length=200, verbose_name='Commit hash')),
                ('commit_json', django.contrib.postgres.fields.jsonb.JSONField()),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='history_service.Links', verbose_name='Link')),
            ],
        ),
    ]
